import streamlit as st
from diffusers import StableDiffusionPipeline
import torch

# Function to generate AI-based images using Huggingface Diffusers
def generate_images_using_huggingface_diffusers(text):
    pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
    pipe = pipe.to("cuda")
    prompt = text
    image = pipe(prompt).images[0]
    return image

# Streamlit Code
st.title("AI Image Generation App with Huggingface Diffusers")
st.subheader("Generate images from text prompts")

input_prompt = st.text_input("Enter your text prompt")
if input_prompt:
    if st.button("Generate Image"):
        st.info("Generating image.....")
        image_output = generate_images_using_huggingface_diffusers(input_prompt)
        st.success("Image Generated Successfully")
        st.image(image_output, caption="Generated by Huggingface Diffusers")
